### ISSUE TITLE
Cannot find saved models

### ISSUE THREAD

**Issue by pradeep-79** [Altaheri/EEG-ATCNet#15]
2024-01-30 20:37:59.364344: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "C:\EEG-ATCNet-main\main_TrainValTest.py", line 425, in <module>
    run()
  File "C:\EEG-ATCNet-main\main_TrainValTest.py", line 421, in run
    test(model, dataset_conf, results_path)    
  File "C:\EEG-ATCNet-main\main_TrainValTest.py", line 246, in test
    runs = os.listdir(results_path+"\\saved models")
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\EEG-ATCNet-main\\results\\saved models'
it is showing this error i'm working on this for past 2 days trying to make it work can someone provide their working code for windows and share their github repository and tell me the exact procedure to run the code

**Comment by Altaheri** [comment]
Hi, download the folder "results\saved models" 
https://github.com/Altaheri/EEG-ATCNet/tree/main/results
